defmodule Glorbo.Config do
  @moduledoc """
  Parser for `~/.glorbo/config.md` — Director-owned runtime config.

  Read once at boot (via `config/runtime.exs`), written on first boot
  when missing. Supplies `secret_key_base`, `dashboard_token`,
  `host`, `port` to the Phoenix endpoint per D-06 / D-07.

  ## File shape

      ---
      secret_key_base: <base-64 string, 64+ bytes of entropy>
      dashboard_token: <url-safe base-64, 32 bytes entropy>   # always required
      host: "127.0.0.1"                # loopback-only by default
      port: 4000
      ---

      # Glorbo configuration
      (free-form markdown notes here; the frontmatter is the contract)

  ## Security

  * The file is written with mode `0600` (Director-only read) on first
    boot. On a fresh Fedora/Debian host this means no other local user
    can read the dashboard token (threat T-04-05).
  * Errors NEVER include field values in messages or logs; `load/1`
    returns opaque `{:error, :config_parse}` on any parse / read issue.
  * `dashboard_token` is auto-generated on first boot (or patched in on
    upgrade from a `null` value) and is always required. MCP clients pass
    it via `Authorization: Bearer <token>`; browsers via `?token=<token>`.
    The token is never written to logs (T-04-05).
  """

  alias Glorbo.Filesystem.Frontmatter

  @type config :: %{
          secret_key_base: String.t(),
          dashboard_token: String.t(),
          host: String.t(),
          port: pos_integer()
        }

  @default_host "127.0.0.1"
  @default_port 4000

  @doc """
  Load the config map from `<base>/config.md`, creating the file with a
  freshly generated `secret_key_base` when absent.

  Returns `{:ok, %{...}}` on success or `{:error, :config_parse}` on any
  failure. The error tuple is value-free to prevent secret leakage into
  logs or process dictionaries (T-04-05).
  """
  @spec load(Path.t()) :: {:ok, config()} | {:error, :config_parse}
  def load(base \\ Glorbo.Filesystem.Hierarchy.default_root()) do
    path = Path.join(base, "config.md")
    unless File.exists?(path), do: write_default!(path)

    with {:ok, content} <- File.read(path),
         {:ok, meta, _body} <- Frontmatter.parse(content),
         {:ok, cfg} <- coerce(meta),
         {:ok, cfg} <- ensure_dashboard_token(path, cfg) do
      {:ok, cfg}
    else
      _ -> {:error, :config_parse}
    end
  end

  # Private — coerce parsed frontmatter to the typed config map. Fills
  # in a generated secret_key_base for frontmatter that lost it (should
  # only happen if the Director hand-edited the file).
  defp coerce(meta) when is_map(meta) do
    secret =
      case meta["secret_key_base"] do
        b when is_binary(b) and byte_size(b) >= 32 -> b
        _ -> generate_secret()
      end

    host =
      case meta["host"] do
        h when is_binary(h) and byte_size(h) > 0 -> h
        _ -> @default_host
      end

    port =
      case meta["port"] do
        p when is_integer(p) and p > 0 and p < 65_536 -> p
        p when is_binary(p) -> parse_port(p)
        _ -> @default_port
      end

    {:ok,
     %{
       secret_key_base: secret,
       dashboard_token: maybe_string(meta["dashboard_token"]),
       host: host,
       port: port
     }}
  end

  defp parse_port(str) do
    case Integer.parse(str) do
      {n, ""} when n > 0 and n < 65_536 -> n
      _ -> @default_port
    end
  end

  defp write_default!(path) do
    File.mkdir_p!(Path.dirname(path))
    secret = generate_secret()
    cookie = generate_cookie()
    token = generate_token()

    body = """
    ---
    kind: config/v1
    secret_key_base: #{secret}
    dashboard_token: #{token}
    erl_cookie: #{cookie}
    host: "127.0.0.1"
    port: 4000
    ---

    # Glorbo configuration

    Generated by Glorbo on first boot. Edit `host:` to `0.0.0.0` to accept
    LAN connections. Keep this file readable only by the Director.
    Set `dashboard_token:` to a fresh value to rotate the auth token.
    MCP clients: use `Authorization: Bearer <token>` on every request.
    """

    atomic_write_secret!(path, body)
  end

  defp generate_secret do
    :crypto.strong_rand_bytes(64) |> Base.encode64()
  end

  # Plan 05-01 (D-25): 24-byte url-safe cookie for Erlang distribution.
  # Url-safe encoding avoids quoting hassles when written to config.md or
  # passed as a `-setcookie` argument via `RELEASE_COOKIE`. 24 bytes
  # (> 128-bit security) exceeds the 16-byte minimum enforced by
  # `erl_cookie/1`.
  defp generate_cookie do
    :crypto.strong_rand_bytes(24) |> Base.url_encode64(padding: false)
  end

  defp generate_token do
    :crypto.strong_rand_bytes(32) |> Base.url_encode64(padding: false)
  end

  defp maybe_string(nil), do: nil
  defp maybe_string(""), do: nil
  defp maybe_string(s) when is_binary(s), do: s
  defp maybe_string(other), do: to_string(other)

  # Auto-generate dashboard_token when nil/empty. Patches config.md in-place
  # using the same line-level rewrite as write_cookie!/5 (T-04-05: token
  # value never appears in log messages).
  defp ensure_dashboard_token(_path, %{dashboard_token: t} = cfg)
       when is_binary(t) and t != "" do
    {:ok, cfg}
  end

  defp ensure_dashboard_token(path, cfg) do
    token = generate_token()

    case patch_dashboard_token(path, token) do
      :ok ->
        :ok

      {:error, reason} ->
        require Logger

        Logger.warning(
          "Failed to persist dashboard_token to config.md: #{inspect(reason)} " <>
            "(token is in-memory only — will change on restart)"
        )
    end

    {:ok, %{cfg | dashboard_token: token}}
  end

  defp patch_dashboard_token(path, token) do
    case File.read(path) do
      {:ok, content} ->
        new_content =
          if Regex.match?(~r/^dashboard_token:/m, content) do
            String.replace(content, ~r/^dashboard_token:.*$/m, "dashboard_token: #{token}")
          else
            # Key entirely absent — inject after the opening fence.
            String.replace(content, "---\n", "---\ndashboard_token: #{token}\n", global: false)
          end

        atomic_write_secret!(path, new_content)
        :ok

      {:error, reason} ->
        {:error, reason}
    end
  rescue
    e -> {:error, Exception.message(e)}
  end

  @doc """
  Return the Erlang distribution cookie for this Glorbo install.

  Ensures the key is present (and ≥ 16 bytes) in `<base>/config.md`; if
  absent or too short, generates a fresh 24-byte url-safe cookie, persists
  it to disk (preserving other frontmatter lines + body), and reasserts
  mode 0600.

  The returned value is opaque — callers MUST treat it as a secret and
  MUST NEVER emit it to logs or audit (threat T-05-02).
  """
  @spec erl_cookie(Path.t()) :: {:ok, String.t()} | {:error, :config_parse}
  def erl_cookie(base \\ Glorbo.Filesystem.Hierarchy.default_root()),
    do: erl_cookie(base, _retried? = false)

  # WR-08: classic TOCTOU — the previous implementation did
  # `unless File.exists?(path), do: write_default!(path)` followed by
  # File.read(path). A concurrent `glorbo init --force` that removed the
  # file in that window landed us in the `:enoent` branch and fell out
  # to {:error, :config_parse}. Handle :enoent explicitly by writing
  # defaults and recursing once (guarded by retried? to prevent loops on
  # unrelated failures).
  defp erl_cookie(base, retried?) do
    path = Path.join(base, "config.md")

    case File.read(path) do
      {:ok, content} ->
        case Frontmatter.parse(content) do
          {:ok, meta, body} -> handle_cookie(path, content, meta, body)
          _ -> {:error, :config_parse}
        end

      {:error, :enoent} when not retried? ->
        write_default!(path)
        erl_cookie(base, true)

      {:error, _} ->
        {:error, :config_parse}
    end
  end

  defp handle_cookie(path, content, meta, body) do
    case meta["erl_cookie"] do
      c when is_binary(c) and byte_size(c) >= 16 ->
        {:ok, c}

      _ ->
        cookie = generate_cookie()
        write_cookie!(path, content, meta, body, cookie)
        {:ok, cookie}
    end
  rescue
    _ -> {:error, :config_parse}
  end

  # Line-level rewrite so we preserve other frontmatter keys, comments
  # (if any sneak past yamerl), and the body verbatim. `:sync` gives us a
  # durable write so a crash mid-write leaves either the old or the new
  # file — never a torn middle.
  defp write_cookie!(path, content, meta, _body, cookie) do
    new_content =
      if Map.has_key?(meta, "erl_cookie") do
        # Replace the single `erl_cookie:` line wherever it sits in the
        # frontmatter — multi-line flag `m` anchors `^`/`$` per line.
        String.replace(content, ~r/^erl_cookie:.*$/m, "erl_cookie: #{cookie}")
      else
        # Inject the key immediately after the opening `---\n` fence
        # (global: false to only touch the first occurrence — the body
        # may contain markdown horizontal rules that look like fences).
        String.replace(content, "---\n", "---\nerl_cookie: #{cookie}\n", global: false)
      end

    atomic_write_secret!(path, new_content)
  end

  # WR-07: write-then-chmod leaves a window where the file is
  # world-readable under the default umask (0644/0664), exposing
  # secret_key_base and erl_cookie to any concurrent local user. Use
  # the same pattern as Pidfile.write!/2: tmp-file write, chmod the
  # tmp, then atomic rename into place. The rename preserves the
  # tmp's mode, so the final path is 0600 from the moment it exists.
  defp atomic_write_secret!(path, content) do
    # Wave 24: random suffix + `:file.open([:exclusive])` closes the
    # predictable-tmpfile-symlink-redirect race that the `path <>
    # ".tmp"` flow had. The exclusive-open path also opens at 0600
    # before the write lands (matches the chmod-then-rename intent
    # without the window where `tmp` is briefly 0644).
    rand_suffix = :crypto.strong_rand_bytes(8) |> Base.encode16(case: :lower)
    tmp = "#{path}.tmp-#{System.unique_integer([:positive, :monotonic])}-#{rand_suffix}"

    {:ok, fd} = :file.open(tmp, [:write, :raw, :exclusive, :binary])

    try do
      :ok = :file.write(fd, content)
    after
      :ok = :file.close(fd)
    end

    File.chmod!(tmp, 0o600)
    File.rename!(tmp, path)
  end
end
