defmodule Glorbo.Config do
  @moduledoc """
  Parser for `~/.glorbo/config.md` — Director-owned runtime config.

  Read once at boot (via `config/runtime.exs`), written on first boot
  when missing. Supplies `secret_key_base`, `dashboard_token` (opt),
  `host`, `port` to the Phoenix endpoint per D-06 / D-07.

  ## File shape

      ---
      secret_key_base: <base-64 string, 64+ bytes of entropy>
      dashboard_token: null            # optional bearer for LAN exposure
      host: "127.0.0.1"                # loopback-only by default
      port: 4000
      ---

      # Glorbo configuration
      (free-form markdown notes here; the frontmatter is the contract)

  ## Security

  * The file is written with mode `0600` (Director-only read) on first
    boot. On a fresh Fedora/Debian host this means no other local user
    can read the dashboard token (threat T-04-05).
  * Errors NEVER include field values in messages or logs; `load/1`
    returns opaque `{:error, :config_parse}` on any parse / read issue.
  """

  alias Glorbo.Filesystem.Frontmatter

  @type config :: %{
          secret_key_base: String.t(),
          dashboard_token: String.t() | nil,
          host: String.t(),
          port: pos_integer()
        }

  @default_host "127.0.0.1"
  @default_port 4000

  @doc """
  Load the config map from `<base>/config.md`, creating the file with a
  freshly generated `secret_key_base` when absent.

  Returns `{:ok, %{...}}` on success or `{:error, :config_parse}` on any
  failure. The error tuple is value-free to prevent secret leakage into
  logs or process dictionaries (T-04-05).
  """
  @spec load(Path.t()) :: {:ok, config()} | {:error, :config_parse}
  def load(base \\ Path.expand("~/.glorbo")) do
    path = Path.join(base, "config.md")
    unless File.exists?(path), do: write_default!(path)

    with {:ok, content} <- File.read(path),
         {:ok, meta, _body} <- Frontmatter.parse(content),
         {:ok, cfg} <- coerce(meta) do
      {:ok, cfg}
    else
      _ -> {:error, :config_parse}
    end
  end

  # Private — coerce parsed frontmatter to the typed config map. Fills
  # in a generated secret_key_base for frontmatter that lost it (should
  # only happen if the Director hand-edited the file).
  defp coerce(meta) when is_map(meta) do
    secret =
      case meta["secret_key_base"] do
        b when is_binary(b) and byte_size(b) >= 32 -> b
        _ -> generate_secret()
      end

    host =
      case meta["host"] do
        h when is_binary(h) and byte_size(h) > 0 -> h
        _ -> @default_host
      end

    port =
      case meta["port"] do
        p when is_integer(p) and p > 0 and p < 65_536 -> p
        p when is_binary(p) -> parse_port(p)
        _ -> @default_port
      end

    {:ok,
     %{
       secret_key_base: secret,
       dashboard_token: maybe_string(meta["dashboard_token"]),
       host: host,
       port: port
     }}
  rescue
    _ -> {:error, :config_parse}
  end

  defp parse_port(str) do
    case Integer.parse(str) do
      {n, ""} when n > 0 and n < 65_536 -> n
      _ -> @default_port
    end
  end

  defp write_default!(path) do
    File.mkdir_p!(Path.dirname(path))
    secret = generate_secret()

    body = """
    ---
    secret_key_base: #{secret}
    dashboard_token: null
    host: "127.0.0.1"
    port: 4000
    ---

    # Glorbo configuration

    Generated by Glorbo on first boot. Edit `host:` to `0.0.0.0` to accept
    LAN connections, and set `dashboard_token:` to require `?token=<...>`
    on the dashboard URL. Keep this file readable only by the Director.
    """

    File.write!(path, body, [:sync])
    File.chmod!(path, 0o600)
  end

  defp generate_secret do
    :crypto.strong_rand_bytes(64) |> Base.encode64()
  end

  defp maybe_string(nil), do: nil
  defp maybe_string(""), do: nil
  defp maybe_string(s) when is_binary(s), do: s
  defp maybe_string(other), do: to_string(other)
end
