defmodule Glorbo.HomeHistory do
  @moduledoc """
  Git-backed durable history for `~/.glorbo/` (GEP-33 Phase 1).

  This module owns the optional, opt-in git repository that lives at
  the home root. It is **derivative**: the working tree under
  `~/.glorbo/` remains the authoritative source of truth (GEP-3). Git
  records changes for diff / log / restore UX without becoming a
  second source of truth.

  Phase 1 scope:

    * `init/1` — bootstrap the repo, write `.gitignore`, stage the
      currently-tracked subset, write the initial commit.
    * `status/1` — wrap `git status --porcelain` against the home
      tree. Reports enabled/disabled + dirty paths.
    * `log/1` — wrap `git log --oneline -n N`.

  Out of scope here (Phase 2+):

    * Marked commits from host-side write surfaces.
    * Watcher-fallback commits for manual edits.
    * `restore`, `show`, `diff` — read-only inspection beyond `log`.

  ## Tracked vs ignored

  Per GEP-33 §3, the repo tracks the durable, user-meaningful subset
  of `~/.glorbo/`:

    * tracked: `companies/<co>/{company.md, projects/**, channels/*.md,
      proposals/*.md, audit/*.jsonl, goals/*.md, skills/*.md,
      agents/<slug>/{AGENT.md, agent.md, SOUL.md, HEARTBEAT.md,
      memory/**, history/**}}`, plus `.gitignore` itself.
    * ignored: `.git/`, `config.md` (carries secrets), `glorbo.db*`,
      `logs/**`, `runtime/**`, `run/**`, `cache/**`, plus per-agent
      `inbox/**`, `outbox/**`, `state/**`, `workspace/**`,
      `stdout.log` (transport / scratch / runtime).

  `.gitignore` encodes the negative half so that git's own
  enumeration matches the tracked-scope rules without us having to
  walk the tree manually.

  ## Author vs committer (Phase 2)

  Phase 1 commits use whatever git env identity the daemon's user
  has — there is no marked-commit pipeline yet. Phase 2 wires the
  `Glorbo Kernel <kernel@glorbo.local>` committer + per-actor author
  identity per GEP-33 §4.2.
  """

  @gitignore """
  # Glorbo home git history — auto-generated by `glorbo history init`.
  # GEP-33 §3.2 — durable state only; secrets, derived data, and
  # transport directories are excluded.

  # Self
  /.git/

  # Secrets
  /config.md

  # Derived state
  /glorbo.db
  /glorbo.db-shm
  /glorbo.db-wal

  # Logs / runtime / cache
  /logs/
  /runtime/
  /run/
  /cache/

  # Per-agent transport + scratch + stdout log
  /companies/*/agents/*/inbox/
  /companies/*/agents/*/outbox/
  /companies/*/agents/*/state/
  /companies/*/agents/*/workspace/
  /companies/*/agents/*/stdout.log
  """

  @type init_result :: %{
          required(:repo) => Path.t(),
          required(:initial_commit) => String.t() | nil,
          required(:tracked) => non_neg_integer()
        }

  @type status_result :: %{
          required(:enabled) => boolean(),
          required(:repo) => Path.t() | nil,
          required(:dirty) => [String.t()]
        }

  # ----------------------------------------------------------------
  # Public API
  # ----------------------------------------------------------------

  @doc """
  Verbatim `.gitignore` content the formatter writes on `init`.
  Public for tests; the constant is the canonical reference.
  """
  @spec gitignore_content() :: String.t()
  def gitignore_content, do: @gitignore

  @doc """
  Bootstrap the history repo at `base` (defaults to `~/.glorbo/`).

  Steps:

    1. Refuse if `base/.git/` already exists (idempotent re-init is a
       Phase 2 follow-up; for now first-run only).
    2. `git init` at `base`.
    3. Write `.gitignore` with the tracked-scope policy.
    4. Stage every tracked file via `git add -A` (the policy lives in
       `.gitignore`, so git's own enumeration matches GEP-33 §3.1).
    5. Commit with subject `glorbo: initial history import`.

  Returns `{:ok, %{repo, initial_commit, tracked}}` on success.
  """
  @spec init(keyword()) :: {:ok, init_result()} | {:error, term()}
  def init(opts \\ []) do
    base = Keyword.get_lazy(opts, :base, &default_base/0)

    with :ok <- ensure_base_exists(base),
         :ok <- ensure_no_existing_repo(base),
         :ok <- git_init(base),
         :ok <- write_gitignore(base),
         :ok <- git_add_all(base),
         {:ok, sha, count} <- git_initial_commit(base) do
      {:ok, %{repo: Path.join(base, ".git"), initial_commit: sha, tracked: count}}
    end
  end

  @doc """
  Report repo state at `base`. When the repo is not initialised
  returns `%{enabled: false, repo: nil, dirty: []}`. Otherwise runs
  `git status --porcelain` and returns the list of changed-tracked
  paths.
  """
  @spec status(keyword()) :: {:ok, status_result()} | {:error, term()}
  def status(opts \\ []) do
    base = Keyword.get_lazy(opts, :base, &default_base/0)

    if File.dir?(Path.join(base, ".git")) do
      # Use `-z` so git emits NUL-separated records and quotes
      # nothing — this side-steps the C-style escaping git applies
      # to paths with newlines/quotes in the default porcelain
      # output (which would otherwise reach the user as e.g.
      # `"path with\\nnewline"` instead of the original bytes).
      case git(["status", "--porcelain", "-z"], base) do
        {:ok, out} ->
          dirty =
            out
            |> String.split(<<0>>, trim: true)
            |> Enum.map(&parse_porcelain_record/1)

          {:ok, %{enabled: true, repo: Path.join(base, ".git"), dirty: dirty}}

        {:error, _} = err ->
          err
      end
    else
      {:ok, %{enabled: false, repo: nil, dirty: []}}
    end
  end

  # `git status --porcelain -z` emits each record as `XY <space> path`
  # (3 prefix bytes). Keep the status code visible so the caller
  # sees ` M path` (modified-not-staged) vs `?? path` (untracked).
  defp parse_porcelain_record(<<x::binary-size(2), " ", rest::binary>>), do: x <> " " <> rest
  defp parse_porcelain_record(other), do: other

  @doc """
  Read the commit log. `:limit` defaults to 20. Returns one map per
  commit with `:sha` (short), `:subject`, `:author_name`, and
  `:relative_time`.
  """
  @spec log(keyword()) :: {:ok, [map()]} | {:error, term()}
  def log(opts \\ []) do
    base = Keyword.get_lazy(opts, :base, &default_base/0)
    limit = Keyword.get(opts, :limit, 20)

    if File.dir?(Path.join(base, ".git")) do
      # `--no-pager` lives on the git CLI itself, not on `log`. A
      # record-separator format keeps subjects with spaces intact.
      format = "%h%x1f%s%x1f%an%x1f%ar"

      args = [
        "--no-pager",
        "log",
        "-n",
        Integer.to_string(limit),
        "--pretty=format:" <> format
      ]

      case git(args, base) do
        {:ok, ""} ->
          {:ok, []}

        {:ok, out} ->
          rows =
            out
            |> String.split("\n", trim: true)
            |> Enum.map(&parse_log_row/1)

          {:ok, rows}

        {:error, _} = err ->
          err
      end
    else
      {:error, :not_initialised}
    end
  end

  # ----------------------------------------------------------------
  # Tracked-scope predicate
  # ----------------------------------------------------------------

  @doc """
  Pure predicate: would a path under `base` be tracked by the
  history repo? Mirrors the policy `.gitignore` encodes so callers
  that need to decide ahead of `git check-ignore` (audit
  pre-classification, doctor warnings) don't shell out.

  The path may be relative to `base` or absolute. Returns `false`
  for any path outside `base`.
  """
  @spec tracked?(Path.t(), Path.t()) :: boolean()
  def tracked?(path, base) when is_binary(path) and is_binary(base) do
    rel = relativise(path, base)

    case rel do
      :outside -> false
      "" -> false
      r -> not ignored?(r)
    end
  end

  defp relativise(path, base) do
    base_abs = Path.expand(base)
    path_abs = Path.expand(path, base_abs)

    cond do
      path_abs == base_abs -> ""
      String.starts_with?(path_abs, base_abs <> "/") -> Path.relative_to(path_abs, base_abs)
      true -> :outside
    end
  end

  # Mirrors @gitignore. Listed in the same order as the file so a
  # change to one demands a paired change to the other.
  defp ignored?(rel) do
    cond do
      String.starts_with?(rel, ".git/") or rel == ".git" -> true
      rel == "config.md" -> true
      rel == "glorbo.db" or rel == "glorbo.db-shm" or rel == "glorbo.db-wal" -> true
      String.starts_with?(rel, "logs/") -> true
      String.starts_with?(rel, "runtime/") -> true
      String.starts_with?(rel, "run/") -> true
      String.starts_with?(rel, "cache/") -> true
      agent_runtime?(rel) -> true
      true -> false
    end
  end

  # `companies/<co>/agents/<slug>/{inbox,outbox,state,workspace}/...`
  # and `.../stdout.log`. Use a single regex match on the canonical
  # shape; segment-by-segment Path.split would also work but the
  # regex is cheaper and reads more directly.
  defp agent_runtime?(rel) do
    Regex.match?(
      ~r{^companies/[^/]+/agents/[^/]+/(inbox|outbox|state|workspace)(/|$)},
      rel
    ) or
      Regex.match?(~r{^companies/[^/]+/agents/[^/]+/stdout\.log$}, rel)
  end

  # ----------------------------------------------------------------
  # Internals — git invocation + step helpers
  # ----------------------------------------------------------------

  defp default_base do
    System.get_env("GLORBO_HOME") || Glorbo.Filesystem.Hierarchy.default_root()
  end

  defp ensure_base_exists(base) do
    if File.dir?(base), do: :ok, else: {:error, {:base_missing, base}}
  end

  defp ensure_no_existing_repo(base) do
    if File.dir?(Path.join(base, ".git")) do
      {:error, :already_initialised}
    else
      :ok
    end
  end

  defp git_init(base) do
    case git(["init", "--quiet", "--initial-branch=main"], base) do
      {:ok, _} -> :ok
      {:error, _} = err -> err
    end
  end

  defp write_gitignore(base) do
    path = Path.join(base, ".gitignore")
    File.write(path, @gitignore)
  end

  defp git_add_all(base) do
    case git(["add", "-A"], base) do
      {:ok, _} -> :ok
      {:error, _} = err -> err
    end
  end

  defp git_initial_commit(base) do
    # `--allow-empty` so a freshly-scaffolded home (no tracked files
    # beyond .gitignore) still gets a root commit. The .gitignore is
    # always present after `write_gitignore/1`, but if every other
    # tracked file ends up matching some future ignore the commit
    # would be empty without this flag.
    args = [
      "-c",
      "user.email=kernel@glorbo.local",
      "-c",
      "user.name=Glorbo Kernel",
      "commit",
      "--allow-empty",
      "--quiet",
      "-m",
      "glorbo: initial history import"
    ]

    case git(args, base) do
      {:ok, _} ->
        with {:ok, sha} <- git(["rev-parse", "--short", "HEAD"], base),
             {:ok, count_out} <- git(["ls-files"], base) do
          count = count_out |> String.split("\n", trim: true) |> length()
          {:ok, String.trim(sha), count}
        end

      {:error, _} = err ->
        err
    end
  end

  defp parse_log_row(row) do
    case String.split(row, "\x1f") do
      [sha, subject, author, rel] ->
        %{sha: sha, subject: subject, author_name: author, relative_time: rel}

      _ ->
        %{sha: "", subject: row, author_name: "", relative_time: ""}
    end
  end

  # System.cmd wrapper — captures stdout, returns trimmed text on
  # success or `{:error, {:git_failed, exit_code, output}}` on
  # failure. `cd:` keeps the invocation rooted at the home dir
  # without depending on the caller's cwd.
  defp git(args, base) do
    case System.cmd("git", args, cd: base, stderr_to_stdout: true) do
      {out, 0} -> {:ok, String.trim_trailing(out)}
      {out, code} -> {:error, {:git_failed, code, String.trim(out)}}
    end
  end
end
