defmodule Glorbo.HomeHistory do
  @moduledoc """
  Git-backed durable history for `~/.glorbo/` (GEP-33 Phase 1).

  This module owns the optional, opt-in git repository that lives at
  the home root. It is **derivative**: the working tree under
  `~/.glorbo/` remains the authoritative source of truth (GEP-3). Git
  records changes for diff / log / restore UX without becoming a
  second source of truth.

  Phase 1 scope:

    * `init/1` — bootstrap the repo, write `.gitignore`, stage the
      currently-tracked subset, write the initial commit.
    * `status/1` — wrap `git status --porcelain` against the home
      tree. Reports enabled/disabled + dirty paths.
    * `log/1` — wrap `git log --oneline -n N`.
    * `commit_marked/3` (Phase 2a-1) — synchronous primitive that
      stages an explicit list of paths, applies the
      tracked-scope filter, and writes one commit with kernel
      committer + actor author + sanitized GEP-33 §4.3 trailers.
      Best-effort: returns `{:error, _}` on git failure so the
      caller can decide whether to retry / warn / drop the
      commit. **No coalescer / no debouncer / no caller wiring
      yet** — those are Phase 2b and 2c.

  Out of scope here (Phase 2b+):

    * Coalesced begin/mark/flush GenServer with debounce window.
    * Watcher-fallback commits for manual edits.
    * Wiring into Router / Actions / scaffolders / restore.
    * `restore`, `show`, `diff` — read-only inspection beyond `log`.

  ## Tracked vs ignored

  Per GEP-33 §3, the repo tracks the durable, user-meaningful subset
  of `~/.glorbo/`:

    * tracked: `companies/<co>/{company.md, projects/**, channels/*.md,
      proposals/*.md, audit/*.jsonl, goals/*.md, skills/*.md,
      agents/<slug>/{AGENT.md, agent.md, SOUL.md, HEARTBEAT.md,
      memory/**, history/**}}`, plus `.gitignore` itself.
    * ignored: `.git/`, `config.md` (carries secrets),
      `providers.toml` (user-controlled `[env]` may carry provider
      API tokens — C-063), `glorbo.db*`,
      `logs/**`, `runtime/**`, `run/**`, `cache/**`, plus per-agent
      `inbox/**`, `outbox/**`, `state/**`, `workspace/**`,
      `stdout.log` (transport / scratch / runtime).

  `.gitignore` encodes the negative half so that git's own
  enumeration matches the tracked-scope rules without us having to
  walk the tree manually.

  ## Author vs committer (Phase 2)

  Phase 1 commits use whatever git env identity the daemon's user
  has — there is no marked-commit pipeline yet. Phase 2 wires the
  `Glorbo Kernel <kernel@glorbo.local>` committer + per-actor author
  identity per GEP-33 §4.2.
  """

  @gitignore """
  # Glorbo home git history — auto-generated by `glorbo history init`.
  # GEP-33 §3.2 — durable state only; secrets, derived data, and
  # transport directories are excluded.

  # Self
  /.git/

  # Secrets — config.md (key base / dashboard token) and the
  # user-controlled provider registry, whose `[env]` table may carry
  # provider API tokens (C-063). Both are denied so they never enter
  # git objects.
  /config.md
  /providers.toml

  # Derived state
  /glorbo.db
  /glorbo.db-shm
  /glorbo.db-wal

  # Logs / runtime / cache
  /logs/
  /runtime/
  /run/
  /cache/

  # Per-agent transport + scratch + stdout log
  /companies/*/agents/*/inbox/
  /companies/*/agents/*/outbox/
  /companies/*/agents/*/state/
  /companies/*/agents/*/workspace/
  /companies/*/agents/*/stdout.log

  # Retired-agent archive — once retired, an agent's subtree is
  # frozen by definition; the retire event itself is captured in
  # the audit log and (when `Agents.retire/3` is Phase-2c-wired)
  # in a single history commit. Tracking the archive's ongoing
  # filesystem state would balloon the repo with content that
  # can't change.
  /companies/*/agents/.archive/
  """

  @type init_result :: %{
          required(:repo) => Path.t(),
          required(:initial_commit) => String.t() | nil,
          required(:tracked) => non_neg_integer()
        }

  @type status_result :: %{
          required(:enabled) => boolean(),
          required(:repo) => Path.t() | nil,
          required(:dirty) => [String.t()]
        }

  @typedoc """
  Logical actor identity per GEP-33 §4.2. Becomes the commit's
  author; the committer is always `Glorbo Kernel`.
  """
  @type actor ::
          :director
          | {:agent, String.t()}
          | {:mcp, String.t()}
          | :system
          | :external

  @typedoc """
  Required metadata for `commit_marked/3`. Sanitized into
  `Glorbo-Actor`, `Glorbo-Action`, `Glorbo-Target`,
  `Glorbo-Source`, `Glorbo-Paths`, `Glorbo-Tx` trailers per
  GEP-33 §4.3 before being handed to git.
  """
  @type tx_meta :: %{
          required(:actor) => actor(),
          required(:action) => String.t(),
          required(:target) => String.t(),
          optional(:source) => String.t(),
          optional(:tx_id) => String.t()
        }

  @type commit_result :: %{
          required(:sha) => String.t(),
          required(:committed) => non_neg_integer(),
          required(:skipped) => [Path.t()]
        }

  # Sanitization — trailer values pass through these caps before
  # they reach git. The thresholds favour readable subjects + a
  # bounded git-log surface; bumps are cheap if a trailer needs
  # more room (e.g., the `Glorbo-Paths` list, which gets a wider
  # cap explicitly below).
  @max_trailer_value_len 200
  @max_paths_trailer_len 1000
  @max_actor_slug_len 64

  # ----------------------------------------------------------------
  # Public API
  # ----------------------------------------------------------------

  @doc """
  Verbatim `.gitignore` content the formatter writes on `init`.
  Public for tests; the constant is the canonical reference.
  """
  @spec gitignore_content() :: String.t()
  def gitignore_content, do: @gitignore

  @doc """
  Bootstrap the history repo at `base` (defaults to `~/.glorbo/`).

  Steps:

    1. Refuse if `base/.git/` already exists (idempotent re-init is a
       Phase 2 follow-up; for now first-run only).
    2. `git init` at `base`.
    3. Write `.gitignore` with the tracked-scope policy.
    4. Stage every tracked file via `git add -A` (the policy lives in
       `.gitignore`, so git's own enumeration matches GEP-33 §3.1).
    5. Commit with subject `glorbo: initial history import`.

  Returns `{:ok, %{repo, initial_commit, tracked}}` on success.
  """
  @spec init(keyword()) :: {:ok, init_result()} | {:error, term()}
  def init(opts \\ []) do
    base = Keyword.get_lazy(opts, :base, &default_base/0)

    with :ok <- ensure_base_exists(base),
         :ok <- ensure_no_existing_repo(base),
         :ok <- git_init(base),
         :ok <- write_gitignore(base),
         :ok <- git_add_all(base),
         {:ok, sha, count} <- git_initial_commit(base) do
      {:ok, %{repo: Path.join(base, ".git"), initial_commit: sha, tracked: count}}
    end
  end

  @doc """
  Report repo state at `base`. When the repo is not initialised
  returns `%{enabled: false, repo: nil, dirty: []}`. Otherwise runs
  `git status --porcelain` and returns the list of changed-tracked
  paths.
  """
  @spec status(keyword()) :: {:ok, status_result()} | {:error, term()}
  def status(opts \\ []) do
    base = Keyword.get_lazy(opts, :base, &default_base/0)

    if File.dir?(Path.join(base, ".git")) do
      # Use `-z` so git emits NUL-separated records and quotes
      # nothing — this side-steps the C-style escaping git applies
      # to paths with newlines/quotes in the default porcelain
      # output (which would otherwise reach the user as e.g.
      # `"path with\\nnewline"` instead of the original bytes).
      case git(["status", "--porcelain", "-z"], base) do
        {:ok, out} ->
          dirty =
            out
            |> String.split(<<0>>, trim: true)
            |> Enum.map(&parse_porcelain_record/1)

          {:ok, %{enabled: true, repo: Path.join(base, ".git"), dirty: dirty}}

        {:error, _} = err ->
          err
      end
    else
      {:ok, %{enabled: false, repo: nil, dirty: []}}
    end
  end

  # `git status --porcelain -z` emits each record as `XY <space> path`
  # (3 prefix bytes). Keep the status code visible so the caller
  # sees ` M path` (modified-not-staged) vs `?? path` (untracked).
  defp parse_porcelain_record(<<x::binary-size(2), " ", rest::binary>>), do: x <> " " <> rest
  defp parse_porcelain_record(other), do: other

  @doc """
  Read the commit log. `:limit` defaults to 20. Returns one map per
  commit with `:sha` (short), `:subject`, `:author_name`, and
  `:relative_time`.
  """
  @spec log(keyword()) :: {:ok, [map()]} | {:error, term()}
  def log(opts \\ []) do
    base = Keyword.get_lazy(opts, :base, &default_base/0)
    limit = Keyword.get(opts, :limit, 20)

    if File.dir?(Path.join(base, ".git")) do
      # `--no-pager` lives on the git CLI itself, not on `log`. A
      # record-separator format keeps subjects with spaces intact.
      format = "%h%x1f%s%x1f%an%x1f%ar"

      args = [
        "--no-pager",
        "log",
        "-n",
        Integer.to_string(limit),
        "--pretty=format:" <> format
      ]

      case git(args, base) do
        {:ok, ""} ->
          {:ok, []}

        {:ok, out} ->
          rows =
            out
            |> String.split("\n", trim: true)
            |> Enum.map(&parse_log_row/1)

          {:ok, rows}

        {:error, _} = err ->
          err
      end
    else
      {:error, :not_initialised}
    end
  end

  @doc """
  Synchronous one-shot commit: stage an explicit list of paths and
  write one commit with actor-aware author + structured trailers.

  This is the Phase 2a-1 primitive. It does not coalesce, does not
  debounce, does not own any tx state — every call produces (at
  most) one commit. Phase 2b will wrap this in a GenServer that
  buffers calls inside the §6.1 debounce window so multi-file
  logical operations land as one commit.

  Behaviour:

    1. **Filters paths via `tracked?/2`.** Untracked-scope paths
       (e.g., `config.md`, `glorbo.db*`, `runtime/`,
       `agents/<slug>/inbox/`) are excluded and reported in
       `:skipped`. Never invokes `git add -A` (GEP-33 §7).
    2. **No-op cleanly when nothing to commit.** If every path
       is filtered out OR every staged path has no diff against
       HEAD, returns `{:ok, %{sha: "", committed: 0}}` without
       creating a commit.
    3. **Sanitizes trailer values** to single-line bounded
       scalars (GEP-33 §12.2) before handing them to git. Stops
       newline-injection from forging fake trailers.
    4. **Author = actor**, **committer = Glorbo Kernel**
       (GEP-33 §4.2). Different identities — the committer
       never lies about which Erlang process wrote the object.
    5. **Best-effort.** A git failure returns `{:error, _}`; the
       caller (typically a writer that already wrote the file
       authoritatively) decides whether to retry or warn.

  Required `meta`:

    * `:actor` — `:director | {:agent, slug} | {:mcp, client} |
      :system | :external`
    * `:action` — short verb like `"task.approve"`
    * `:target` — canonical path or logical id (used in subject)

  Optional `meta`:

    * `:source` — origin module/function (`"actions.set_approval"`)
    * `:tx_id` — idempotency token; auto-generated otherwise

  Options:

    * `:base` — home root (defaults to `GLORBO_HOME` / hierarchy
      default)

  Returns `{:ok, %{sha, committed, skipped}}` on success;
  `{:error, :not_initialised}` if `.git/` is absent;
  `{:error, :invalid_meta}` if required metadata is missing or
  shaped incorrectly; `{:error, {:git_failed, code, output}}`
  on subprocess failure.
  """
  @spec commit_marked([Path.t()], tx_meta(), keyword()) ::
          {:ok, commit_result()} | {:error, term()}
  def commit_marked(paths, meta, opts \\ []) when is_list(paths) and is_map(meta) do
    base = Keyword.get_lazy(opts, :base, &default_base/0)

    with :ok <- ensure_repo_initialised(base),
         {:ok, validated} <- validate_meta(meta),
         {tracked, skipped} <- partition_tracked_paths(paths, base) do
      if tracked == [] do
        {:ok, %{sha: "", committed: 0, skipped: skipped}}
      else
        do_marked_commit(base, tracked, skipped, validated)
      end
    end
  end

  @doc """
  Translate the free-form actor label that Glorbo writers carry
  (`"director"`, `"agent:ceo"`, `"mcp:claude-code"`, `"system"`,
  `"external"`) into the GEP-33 §4.2 `actor()` variants
  `commit_marked/3` expects. Unknown shapes default to `:system`
  so writers degrade to system-level provenance without losing
  the commit. Phase 2c writers all funnel through here.
  """
  @spec actor_from_string(String.t()) :: actor()
  def actor_from_string("director"), do: :director
  def actor_from_string("system"), do: :system
  def actor_from_string("external"), do: :external

  def actor_from_string("agent:" <> slug) when slug != "" do
    {:agent, slug}
  end

  def actor_from_string("mcp:" <> client) when client != "" do
    {:mcp, client}
  end

  def actor_from_string(_), do: :system

  @doc """
  Compute the absolute path of the current month's audit jsonl
  for a given company. Phase 2c writers mark this alongside their
  primary file write so the §6.1 inactivity window fires one
  combined commit.
  """
  @spec audit_jsonl_path(Path.t(), String.t()) :: Path.t()
  def audit_jsonl_path(base, company) when is_binary(base) and is_binary(company) do
    {{y, m, _d}, _time} = :calendar.universal_time()
    month = :io_lib.format("~4..0B-~2..0B", [y, m]) |> IO.iodata_to_binary()
    Path.join([base, "companies", company, "audit", month <> ".jsonl"])
  end

  @doc """
  Public version of the home-root resolver: `GLORBO_HOME` env var
  if set, otherwise the hierarchy default. Phase 3 watcher bridge
  needs this when its own `:base` opt is absent at boot.
  """
  @spec default_base!() :: Path.t()
  def default_base!, do: default_base()

  @doc """
  Show a single commit (`git show --stat <rev>`). Returns
  `{:ok, output}` with the formatted text on success.

  GEP-33 Phase 4: Director-facing history archaeology.
  """
  @spec show(String.t(), keyword()) :: {:ok, String.t()} | {:error, term()}
  def show(rev, opts \\ []) when is_binary(rev) do
    base = Keyword.get_lazy(opts, :base, &default_base/0)

    with :ok <- ensure_repo_initialised(base),
         :ok <- validate_rev(rev) do
      case git(["show", "--stat", rev], base) do
        {:ok, out} -> {:ok, out}
        {:error, _} = err -> err
      end
    end
  end

  @doc """
  Diff two revs (or one rev vs working tree). Mirrors
  `git diff <rev1>..<rev2>` (two-rev) or `git diff <rev>` (one
  rev → working tree).

  Optional `:path` opt scopes the diff to one file.
  """
  @spec diff(String.t(), String.t() | nil, keyword()) ::
          {:ok, String.t()} | {:error, term()}
  def diff(rev1, rev2 \\ nil, opts \\ []) when is_binary(rev1) do
    base = Keyword.get_lazy(opts, :base, &default_base/0)
    path_opt = Keyword.get(opts, :path)

    with :ok <- ensure_repo_initialised(base),
         :ok <- validate_rev(rev1),
         :ok <- maybe_validate_rev(rev2),
         :ok <- maybe_validate_path(path_opt) do
      args =
        case rev2 do
          nil -> ["diff", rev1]
          r2 when is_binary(r2) -> ["diff", "#{rev1}..#{r2}"]
        end

      args = if path_opt, do: args ++ ["--", path_opt], else: args

      case git(args, base) do
        {:ok, out} -> {:ok, out}
        {:error, _} = err -> err
      end
    end
  end

  @doc """
  Restore a single tracked path from a previous revision into the
  working tree, then create a new commit describing the restore
  (append-only repo semantics — restore is itself a recordable
  event).

  `path` is relative to the home root. Refuses to restore
  excluded-scope paths or paths outside the repo.

  Required `meta`:

    * `:actor` — who initiated the restore (typically `:director`).

  Optional:

    * `:confirm` — when `false`, returns
      `{:ok, %{would_restore: path, head_commit: sha}}` without
      mutating the working tree (dry-run).
  """
  @spec restore(String.t(), Path.t(), tx_meta(), keyword()) ::
          {:ok, map()} | {:error, term()}
  def restore(rev, path, meta, opts \\ [])
      when is_binary(rev) and is_binary(path) and is_map(meta) do
    base = Keyword.get_lazy(opts, :base, &default_base/0)
    confirm? = Keyword.get(opts, :confirm, true)

    with :ok <- ensure_repo_initialised(base),
         :ok <- validate_rev(rev),
         :ok <- validate_path(path),
         :ok <- ensure_tracked_scope(path, base) do
      if confirm? do
        do_restore(base, rev, path, meta)
      else
        {:ok, head} = git(["rev-parse", "--short", "HEAD"], base)
        {:ok, %{would_restore: path, head_commit: String.trim(head)}}
      end
    end
  end

  defp do_restore(base, rev, path, meta) do
    rel = relativise(path, base)
    rel_str = if rel == :outside, do: path, else: rel

    case git(["checkout", rev, "--", rel_str], base) do
      {:ok, _} ->
        # Stage + commit the restore as a new history entry. The
        # restore-as-commit pattern keeps the repo append-only
        # from the user's perspective: HEAD always advances, never
        # rewinds.
        restore_meta = %{
          actor: Map.get(meta, :actor, :director),
          action: "history.restore",
          target: rel_str,
          source: "history.restore from #{rev}"
        }

        abs_path = Path.expand(rel_str, Path.expand(base))
        commit_marked([abs_path], restore_meta, base: base)

      {:error, _} = err ->
        err
    end
  end

  # Rev validation: refuse anything that could confuse git's
  # argument parser or smuggle a second logical arg. `\t`, `\n`,
  # `\r`, NUL, and other control chars are all rejected; bare
  # spaces likewise. Leading `-` is the option-injection vector
  # (`-c`, `--upload-pack=...`); reject too. `git rev-parse
  # --verify` is the strict resolver downstream — this is
  # defense-in-depth.
  defp validate_rev(rev) do
    cond do
      not is_binary(rev) -> {:error, :invalid_rev}
      rev == "" -> {:error, :invalid_rev}
      Regex.match?(~r/[\s\x00-\x1f\x7f]/, rev) -> {:error, :invalid_rev}
      String.starts_with?(rev, "-") -> {:error, :invalid_rev}
      true -> :ok
    end
  end

  defp maybe_validate_rev(nil), do: :ok
  defp maybe_validate_rev(rev), do: validate_rev(rev)

  defp validate_path(""), do: {:error, :invalid_path}

  # Path validation: same control-char + NUL guard as
  # `validate_rev/1`. NUL is especially load-bearing — Linux
  # syscalls truncate paths at the first NUL, so a path like
  # `"safe.md\0/etc/passwd"` would fool `String.contains?(path,
  # "..")` while opening `safe.md` at the syscall layer (and an
  # attacker who can supply such a path probably wants to fool
  # `tracked?/2` into believing one path while git operates on
  # another).
  defp validate_path(path) when is_binary(path) do
    cond do
      Regex.match?(~r/[\x00-\x1f\x7f]/, path) -> {:error, :invalid_path}
      String.starts_with?(path, "-") -> {:error, :invalid_path}
      String.starts_with?(path, "/") -> {:error, :invalid_path}
      String.contains?(path, "..") -> {:error, :invalid_path}
      true -> :ok
    end
  end

  defp validate_path(_), do: {:error, :invalid_path}

  defp maybe_validate_path(nil), do: :ok
  defp maybe_validate_path(path), do: validate_path(path)

  defp ensure_tracked_scope(path, base) do
    abs_path = Path.expand(path, Path.expand(base))
    if tracked?(abs_path, base), do: :ok, else: {:error, :path_excluded}
  end

  @doc """
  Public sanitizer used by `commit_marked/3` and exposed for
  tests + future Phase-2b callers that need to pre-sanitize meta
  before queueing it.

  Strips control characters (including newlines), trims
  whitespace, and bounds length. Non-binary input is coerced via
  `to_string/1`.
  """
  @spec sanitize_trailer(term()) :: String.t()
  def sanitize_trailer(value, max_len \\ @max_trailer_value_len)

  def sanitize_trailer(nil, _), do: ""

  def sanitize_trailer(value, max_len) when is_binary(value) do
    value
    |> String.replace(~r/[\x00-\x1f\x7f]+/, " ")
    |> String.trim()
    |> String.slice(0, max_len)
  end

  def sanitize_trailer(value, max_len), do: sanitize_trailer(to_string(value), max_len)

  # ----------------------------------------------------------------
  # Tracked-scope predicate
  # ----------------------------------------------------------------

  @doc """
  Pure predicate: would a path under `base` be tracked by the
  history repo? Mirrors the policy `.gitignore` encodes so callers
  that need to decide ahead of `git check-ignore` (audit
  pre-classification, doctor warnings) don't shell out.

  The path may be relative to `base` or absolute. Returns `false`
  for any path outside `base`.
  """
  @spec tracked?(Path.t(), Path.t()) :: boolean()
  def tracked?(path, base) when is_binary(path) and is_binary(base) do
    rel = relativise(path, base)

    case rel do
      :outside -> false
      "" -> false
      r -> not ignored?(r)
    end
  end

  defp relativise(path, base) do
    base_abs = Path.expand(base)
    path_abs = Path.expand(path, base_abs)

    cond do
      path_abs == base_abs -> ""
      String.starts_with?(path_abs, base_abs <> "/") -> Path.relative_to(path_abs, base_abs)
      true -> :outside
    end
  end

  # Mirrors @gitignore. Listed in the same order as the file so a
  # change to one demands a paired change to the other.
  defp ignored?(rel) do
    cond do
      String.starts_with?(rel, ".git/") or rel == ".git" -> true
      rel == "config.md" -> true
      rel == "providers.toml" -> true
      rel == "glorbo.db" or rel == "glorbo.db-shm" or rel == "glorbo.db-wal" -> true
      String.starts_with?(rel, "logs/") -> true
      String.starts_with?(rel, "runtime/") -> true
      String.starts_with?(rel, "run/") -> true
      String.starts_with?(rel, "cache/") -> true
      agent_runtime?(rel) -> true
      true -> false
    end
  end

  # `companies/<co>/agents/<slug>/{inbox,outbox,state,workspace}/...`
  # and `.../stdout.log`. Use a single regex match on the canonical
  # shape; segment-by-segment Path.split would also work but the
  # regex is cheaper and reads more directly.
  defp agent_runtime?(rel) do
    Regex.match?(
      ~r{^companies/[^/]+/agents/[^/]+/(inbox|outbox|state|workspace)(/|$)},
      rel
    ) or
      Regex.match?(~r{^companies/[^/]+/agents/[^/]+/stdout\.log$}, rel) or
      Regex.match?(~r{^companies/[^/]+/agents/\.archive(/|$)}, rel)
  end

  # ----------------------------------------------------------------
  # Internals — git invocation + step helpers
  # ----------------------------------------------------------------

  defp default_base do
    System.get_env("GLORBO_HOME") || Glorbo.Filesystem.Hierarchy.default_root()
  end

  defp ensure_base_exists(base) do
    if File.dir?(base), do: :ok, else: {:error, {:base_missing, base}}
  end

  defp ensure_no_existing_repo(base) do
    if File.dir?(Path.join(base, ".git")) do
      {:error, :already_initialised}
    else
      :ok
    end
  end

  defp git_init(base) do
    case git(["init", "--quiet", "--initial-branch=main"], base) do
      {:ok, _} -> :ok
      {:error, _} = err -> err
    end
  end

  defp write_gitignore(base) do
    path = Path.join(base, ".gitignore")
    File.write(path, @gitignore)
  end

  defp git_add_all(base) do
    case git(["add", "-A"], base) do
      {:ok, _} -> :ok
      {:error, _} = err -> err
    end
  end

  defp git_initial_commit(base) do
    # `--allow-empty` so a freshly-scaffolded home (no tracked files
    # beyond .gitignore) still gets a root commit. The .gitignore is
    # always present after `write_gitignore/1`, but if every other
    # tracked file ends up matching some future ignore the commit
    # would be empty without this flag.
    args =
      kernel_committer_args() ++
        [
          "commit",
          "--allow-empty",
          "--quiet",
          "-m",
          "glorbo: initial history import"
        ]

    case git(args, base) do
      {:ok, _} ->
        with {:ok, sha} <- git(["rev-parse", "--short", "HEAD"], base),
             {:ok, count_out} <- git(["ls-files"], base) do
          count = count_out |> String.split("\n", trim: true) |> length()
          {:ok, String.trim(sha), count}
        end

      {:error, _} = err ->
        err
    end
  end

  defp kernel_committer_args do
    ["-c", "user.email=kernel@glorbo.local", "-c", "user.name=Glorbo Kernel"]
  end

  defp ensure_repo_initialised(base) do
    if File.dir?(Path.join(base, ".git")) do
      :ok
    else
      {:error, :not_initialised}
    end
  end

  defp partition_tracked_paths(paths, base) do
    {scope_ok, scope_skipped} =
      paths
      |> Enum.uniq()
      |> Enum.split_with(&tracked?(&1, base))

    # Existence-or-in-HEAD check: a writer may mark a path
    # optimistically before the corresponding write lands on disk
    # (audit jsonl async-written by AuditLog GenServer); marked
    # paths that match neither working tree nor HEAD's tree would
    # cause `git add -A -- <path>` to fail with "did not match any
    # files." Drop those into `:skipped` rather than failing the
    # whole commit. Paths that are gone from disk but PRESENT in
    # HEAD still pass through — `git add -A` will stage their
    # deletion (channels.archive src, etc.).
    {tracked_rel, missing} =
      scope_ok
      |> Enum.split_with(fn p ->
        File.exists?(Path.expand(p, Path.expand(base))) or
          in_head?(p, base)
      end)
      |> then(fn {present, missing} ->
        {Enum.map(present, &relativise_or_keep(&1, base)), missing}
      end)

    {tracked_rel, scope_skipped ++ missing}
  end

  defp in_head?(path, base) do
    rel =
      case relativise(path, base) do
        :outside -> path
        "" -> path
        r -> r
      end

    case System.cmd("git", ["cat-file", "-e", "HEAD:" <> rel],
           cd: base,
           stderr_to_stdout: true
         ) do
      {_, 0} -> true
      _ -> false
    end
  end

  defp relativise_or_keep(path, base) do
    case relativise(path, base) do
      :outside -> path
      "" -> path
      rel -> rel
    end
  end

  defp validate_meta(meta) do
    with {:ok, actor} <- fetch_actor(meta),
         {:ok, action} <- fetch_required_string(meta, :action),
         {:ok, target} <- fetch_required_string(meta, :target),
         {:ok, author} <- format_author(actor),
         actor_label <- format_actor_label(actor),
         source <- sanitize_trailer(Map.get(meta, :source, "")),
         tx_id <- ensure_tx_id(meta) do
      {:ok,
       %{
         author: author,
         actor: actor_label,
         action: sanitize_trailer(action),
         target: sanitize_trailer(target),
         source: source,
         tx_id: tx_id
       }}
    end
  end

  defp fetch_actor(meta) do
    case Map.fetch(meta, :actor) do
      {:ok, actor} ->
        if valid_actor?(actor), do: {:ok, actor}, else: {:error, :invalid_meta}

      :error ->
        {:error, :invalid_meta}
    end
  end

  defp valid_actor?(:director), do: true
  defp valid_actor?(:system), do: true
  defp valid_actor?(:external), do: true
  defp valid_actor?({:agent, slug}) when is_binary(slug) and byte_size(slug) > 0, do: true
  defp valid_actor?({:mcp, client}) when is_binary(client) and byte_size(client) > 0, do: true
  defp valid_actor?(_), do: false

  defp fetch_required_string(meta, key) do
    case Map.get(meta, key) do
      v when is_binary(v) and byte_size(v) > 0 -> {:ok, v}
      _ -> {:error, :invalid_meta}
    end
  end

  defp format_author(:director), do: {:ok, "Director <director@glorbo.local>"}
  defp format_author(:system), do: {:ok, "System <system@glorbo.local>"}
  defp format_author(:external), do: {:ok, "External <external@glorbo.local>"}

  defp format_author({:agent, slug}) do
    case sanitize_actor_slug(slug) do
      "" -> {:error, :invalid_meta}
      s -> {:ok, "Agent #{s} <agent+#{s}@glorbo.local>"}
    end
  end

  defp format_author({:mcp, client}) do
    case sanitize_actor_slug(client) do
      "" -> {:error, :invalid_meta}
      c -> {:ok, "MCP #{c} <mcp+#{c}@glorbo.local>"}
    end
  end

  defp format_actor_label(:director), do: "director"
  defp format_actor_label(:system), do: "system"
  defp format_actor_label(:external), do: "external"
  defp format_actor_label({:agent, slug}), do: "agent:" <> sanitize_actor_slug(slug)
  defp format_actor_label({:mcp, client}), do: "mcp:" <> sanitize_actor_slug(client)

  # Actor slugs flow into a left-hand-side email local part, so cap
  # to RFC-safe characters. A dropped slug returns "" — caller treats
  # that as invalid_meta.
  defp sanitize_actor_slug(slug) do
    slug
    |> String.replace(~r/[^a-zA-Z0-9._-]/, "")
    |> String.slice(0, @max_actor_slug_len)
  end

  defp ensure_tx_id(meta) do
    case Map.get(meta, :tx_id) do
      v when is_binary(v) and byte_size(v) > 0 -> sanitize_trailer(v)
      _ -> generate_tx_id()
    end
  end

  defp generate_tx_id do
    random = :crypto.strong_rand_bytes(10) |> Base.encode32(case: :lower, padding: false)
    "history-" <> random
  end

  defp do_marked_commit(base, tracked, skipped, validated) do
    with :ok <- git_add_paths(base, tracked),
         {:ok, sha_or_noop} <- git_commit_or_noop(base, tracked, validated) do
      {:ok, %{sha: sha_or_noop, committed: commit_count(sha_or_noop, tracked), skipped: skipped}}
    end
  end

  defp commit_count("", _), do: 0
  defp commit_count(_sha, tracked), do: length(tracked)

  defp git_add_paths(base, paths) do
    # `git add -A -- <path>` stages adds + modifies + DELETIONS for
    # the specific pathspec — necessary so writers that move/delete
    # tracked files (`Agents.retire`, `Tasks.trash`,
    # `Channels.archive`) can commit the deletion without a
    # separate `git rm` pass. Per GEP-33 §7 the prohibition is on
    # the WHOLE-REPO `git add -A` (no pathspec); restricting `-A`
    # to an explicit pathspec preserves the "never bulk-stage" rule
    # while letting deletions land naturally.
    #
    # Non-existent paths that are also absent from HEAD become a
    # silent no-op (git stages nothing) — the same shape the old
    # existence-filter produced, but without the up-front
    # `File.exists?/1` check. Audit jsonls written async by the
    # AuditLog GenServer are the motivating case.
    Enum.reduce_while(paths, :ok, fn rel, _ ->
      case git(["add", "-A", "--", rel], base) do
        {:ok, _} -> {:cont, :ok}
        {:error, _} = err -> {:halt, err}
      end
    end)
  end

  # `git diff --cached --quiet` exits 0 when the index matches HEAD
  # (nothing to commit) and 1 when there's a real diff. Anything else
  # is a real error.
  defp git_commit_or_noop(base, tracked, validated) do
    case System.cmd("git", ["diff", "--cached", "--quiet"], cd: base, stderr_to_stdout: true) do
      {_, 0} -> {:ok, ""}
      {_, 1} -> do_kernel_commit(base, tracked, validated)
      {out, code} -> {:error, {:git_failed, code, String.trim(out)}}
    end
  end

  defp do_kernel_commit(base, tracked, validated) do
    %{author: author, action: action, target: target, source: source, tx_id: tx_id} = validated

    subject = "#{action}: #{target}"
    paths_value = build_paths_trailer_value(tracked)

    trailers =
      [
        {"Glorbo-Actor", validated.actor},
        {"Glorbo-Action", action},
        {"Glorbo-Target", target}
      ] ++
        if(source == "", do: [], else: [{"Glorbo-Source", source}]) ++
        [{"Glorbo-Paths", paths_value}, {"Glorbo-Tx", tx_id}]

    message =
      subject <>
        "\n\n" <> Enum.map_join(trailers, "\n", fn {k, v} -> "#{k}: #{v}" end) <> "\n"

    args =
      kernel_committer_args() ++
        [
          "commit",
          "--quiet",
          "--no-verify",
          "--author=#{author}",
          "-m",
          message
        ]

    case git(args, base) do
      {:ok, _} ->
        case git(["rev-parse", "--short", "HEAD"], base) do
          {:ok, sha} -> {:ok, String.trim(sha)}
          {:error, _} = err -> err
        end

      {:error, _} = err ->
        err
    end
  end

  defp build_paths_trailer_value(tracked) do
    tracked
    |> Enum.map(&sanitize_trailer/1)
    |> Enum.reject(&(&1 == ""))
    |> Enum.join(", ")
    |> sanitize_trailer(@max_paths_trailer_len)
  end

  defp parse_log_row(row) do
    case String.split(row, "\x1f") do
      [sha, subject, author, rel] ->
        %{sha: sha, subject: subject, author_name: author, relative_time: rel}

      _ ->
        %{sha: "", subject: row, author_name: "", relative_time: ""}
    end
  end

  # System.cmd wrapper — captures stdout, returns trimmed text on
  # success or `{:error, {:git_failed, exit_code, output}}` on
  # failure. `cd:` keeps the invocation rooted at the home dir
  # without depending on the caller's cwd.
  defp git(args, base) do
    case System.cmd("git", args, cd: base, stderr_to_stdout: true) do
      {out, 0} -> {:ok, String.trim_trailing(out)}
      {out, code} -> {:error, {:git_failed, code, String.trim(out)}}
    end
  end
end
