defmodule GlorboWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :glorbo

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_glorbo_key",
    signing_salt: "qLM7LEAG",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :glorbo,
    gzip: not code_reloading?,
    only: GlorboWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :glorbo
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # `:length` caps the body Plug.Parsers will buffer before rejecting.
  # Without this, an MCP client could POST a multi-gigabyte JSON blob
  # and the BEAM would accumulate the whole body before any tool-layer
  # size check ran. 1 MiB is well above every known call shape:
  # brain-dump captures are 64 KiB, messages 10 KiB, proposals a few
  # KiB. A request larger than this gets `413 Request Entity Too Large`
  # before hitting the router.
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    length: 1_048_576

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug GlorboWeb.Router
end
