defmodule GlorboWeb.Router do
  use GlorboWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, html: {GlorboWeb.Layouts, :root}
    plug :protect_from_forgery

    # Wave 28b defense-in-depth: layer a Content-Security-Policy on
    # top of Phoenix's default secure-header set. The dashboard is
    # localhost-only, so the threat is XSS via agent-rendered chat /
    # task body content (sanitised by HtmlSanitizeEx, but CSP is the
    # second line). Settings keep LiveView working:
    #   * `default-src 'self'` blocks any external resource by default
    #   * `script-src 'self'` blocks third-party JS — `app.js` is bundled
    #   * `style-src 'self' 'unsafe-inline' cdnjs.cloudflare.com` —
    #     unsafe-inline kept for HEEx-inlined styles; cdn entry for
    #     font-awesome (already SRI-pinned in root layout)
    #   * `font-src 'self' cdnjs.cloudflare.com data:` — same cdn
    #   * `img-src 'self' data:` — data: needed for inline SVG icons
    #   * `connect-src 'self'` — LiveView WS is same-origin
    #   * `frame-ancestors 'none'` — no clickjacking
    #   * `base-uri 'self'` — block <base> hijack
    #   * `form-action 'self'` — block off-site form submission
    plug :put_secure_browser_headers, %{
      "content-security-policy" =>
        "default-src 'self'; " <>
          "script-src 'self'; " <>
          "style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; " <>
          "font-src 'self' https://cdnjs.cloudflare.com data:; " <>
          "img-src 'self' data:; " <>
          "connect-src 'self'; " <>
          "frame-ancestors 'none'; " <>
          "base-uri 'self'; " <>
          "form-action 'self'"
    }
  end

  # Always-enforced bearer-token gate (D-06, GEP-48). `dashboard_token:`
  # is mandatory (auto-generated by Config.load), so this pipeline never
  # passes an unauthenticated request. Browsers authenticate once via
  # `?token=` and ride a session cookie thereafter; MCP/CLI send the
  # `Authorization: Bearer` header per request.
  pipeline :dashboard do
    plug GlorboWeb.Plugs.DashboardToken
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GlorboWeb do
    pipe_through [:browser, :dashboard]

    # Plan 04-02 Task 1: dashboard entry + company-scope routes.
    # /health-legacy keeps the Phase 1 health probe available; 04-03
    # mounts HealthLive at /health below.
    get "/", PageController, :redirect_to_companies
    get "/health-legacy", PageController, :health

    live "/companies", OverviewLive
    live "/companies/:company", CompanyLive
    live "/companies/:company/kanban", KanbanLive
    live "/companies/:company/projects/:project", ProjectLive
    # Dedicated task-detail page — JIRA-style. Kanban opens the same task
    # as a right-side shelf; clicking "open task page →" navigates here.
    live "/companies/:company/tasks/:task_id", TaskLive
    # GEP-40 chain audit view: task's handoff_chain + reconciled
    # `task.reassign` audit events, for "how did we get here" forensics.
    live "/companies/:company/tasks/:task_id/chain", TaskChainLive
    live "/companies/:company/agents/:agent", AgentLive
    # Unified director inbox — approvals + recent activity + future
    # @mention and assignment feeds. The standalone `/approvals`
    # route was folded in here (backlog #14) — Inbox's Mine tab
    # renders the same awaiting-approval sentinels with approve /
    # deny / archive buttons.
    live "/companies/:company/inbox", InboxLive
    # Plan 04-03 Task 2: content-scope chat view.
    live "/companies/:company/channels/:channel", ChannelLive
    # Director ↔ agent DM: delegates to ChannelLive with a reserved
    # `dm-director--<agent>` channel name; auto-creates the file.
    get "/companies/:company/dms/:agent", PageController, :redirect_to_dm
    # Plan 04-03 Task 3: audit viewer + system health.
    live "/companies/:company/audit", AuditLive
    # paperclip-ux-gaps §7 — dedicated goals page.
    live "/companies/:company/goals", GoalsLive
    # GEP-28 — agent-created proposals (hire, fire, budget, project,
    # custom). Mirrors the approval queue shape but lives on its own
    # route so the unified inbox isn't the only entry point.
    live "/companies/:company/proposals", ProposalsLive
    # paperclip-ux-gaps §9 — skills marketplace / bundle view.
    # Read-only listing of skills available to this company's agents;
    # "builtin" = ships with Glorbo under priv/templates/skills,
    # "custom" = `<base>/skills/<name>.md` user overrides.
    live "/companies/:company/skills", SkillsLive
    # T1-E brain dump (#230) — daily append-only capture log.
    live "/companies/:company/braindump", BrainDumpLive
    # #259 — CSV export of the current month's audit log.
    get "/companies/:company/audit.csv", AuditExportController, :export
    # Localforge bridge #3: unified live activity feed. Subscribes to
    # the global `audit:all` topic; one row per audit append across
    # every company.
    live "/activity", ActivityLive
    live "/health", HealthLive
    # GEP-8 — provider registry dashboard.
    live "/providers", ProvidersLive
    # GEP-26 Phase B — benchmark runs (A/B provider comparison).
    # BenchmarksLive is the index, BenchLive is the per-run blind
    # scoring view. Both read from ~/.glorbo/benchmarks/runs/*.
    live "/benchmarks", BenchmarksLive
    live "/benchmarks/:run_id", BenchLive
    # T2-D (#242) — cross-company monthly cost ledger.
    live "/costs", CostsLive
  end

  # T2-B (#232) — Ctrl+K content search. JSON endpoint consumed by
  # the palette. Pipes through :api AND :dashboard — the same bearer-
  # token gate that protects the LiveView surface also protects this
  # endpoint on LAN exposure. Otherwise, with `dashboard_token:` set,
  # the browser UI would be gated but task titles would be enumerable
  # via `curl /api/search?co=<slug>&q=<prefix>`.
  scope "/api", GlorboWeb do
    pipe_through [:api, :dashboard]

    get "/search", SearchController, :search
  end

  # GEP-29 wave (a) — Model Context Protocol server.
  # Streamable HTTP transport, single endpoint. Wrapped in the
  # `:dashboard` pipeline (threatmodel T11): if `dashboard_token` is
  # configured, MCP clients must pass it via `Authorization: Bearer
  # <token>` or `?token=<token>`. Without a configured token the
  # pipeline is a no-op and loopback binding + host-user trust is the
  # outer boundary. The MCP plug keeps its own Origin check for
  # DNS-rebind protection.
  scope "/" do
    pipe_through :dashboard

    forward "/mcp", GlorboWeb.MCP.Plug
  end
end
