defmodule GlorboWeb.Router do
  use GlorboWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, html: {GlorboWeb.Layouts, :root}
    plug :protect_from_forgery

    # Wave 28b defense-in-depth: layer a Content-Security-Policy on
    # top of Phoenix's default secure-header set. The dashboard is
    # localhost-only, so the threat is XSS via agent-rendered chat /
    # task body content (sanitised by HtmlSanitizeEx, but CSP is the
    # second line). Settings keep LiveView working:
    #   * `default-src 'self'` blocks any external resource by default
    #   * `script-src 'self'` blocks third-party JS — `app.js` is bundled
    #   * `style-src 'self' 'unsafe-inline' cdnjs.cloudflare.com` —
    #     unsafe-inline kept for HEEx-inlined styles; cdn entry for
    #     font-awesome (already SRI-pinned in root layout)
    #   * `font-src 'self' cdnjs.cloudflare.com data:` — same cdn
    #   * `img-src 'self' data:` — data: needed for inline SVG icons
    #   * `connect-src 'self'` — LiveView WS is same-origin
    #   * `frame-ancestors 'none'` — no clickjacking
    #   * `base-uri 'self'` — block <base> hijack
    #   * `form-action 'self'` — block off-site form submission
    plug :put_secure_browser_headers, %{
      "content-security-policy" =>
        "default-src 'self'; " <>
          "script-src 'self'; " <>
          "style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; " <>
          "font-src 'self' https://cdnjs.cloudflare.com data:; " <>
          "img-src 'self' data:; " <>
          "connect-src 'self'; " <>
          "frame-ancestors 'none'; " <>
          "base-uri 'self'; " <>
          "form-action 'self'"
    }
  end

  # Always-enforced bearer-token gate (D-06, GEP-48). `dashboard_token:`
  # is mandatory (auto-generated by Config.load), so this pipeline never
  # passes an unauthenticated request. MCP/CLI send the `Authorization:
  # Bearer` header per request. GEP-0053: this gate is now MCP/CLI-only —
  # the browser dashboard moved to the passphrase gate below, so a token
  # leak no longer grants dashboard access once a passphrase is set.
  pipeline :dashboard do
    plug GlorboWeb.Plugs.DashboardToken
  end

  # GEP-0053: browser dashboard gate. Requires a director passphrase
  # session (or funnels to /setup in bootstrap, 503s when degraded). The
  # token grants NO browser access here (D2).
  pipeline :dashboard_browser do
    plug GlorboWeb.DirectorAuth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # GEP-0053: browser-owned JSON endpoints (the Ctrl+K search palette).
  # These serve dashboard data to the authenticated browser, so they must
  # ride the SAME passphrase gate as the dashboard — not the dashboard_token
  # (which is MCP/CLI-only once configured, D2). Same-origin browser fetches
  # carry the session cookie, so DirectorAuth authorises them.
  pipeline :dashboard_api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug GlorboWeb.DirectorAuth
  end

  # GEP-0053 auth entry points. `:browser` only (so `:protect_from_forgery`
  # covers the POST forms) — NOT behind DirectorAuth, since these ARE the
  # way in. Each action enforces its own state precondition (setup =
  # bootstrap + token; login = configured; logout = any). No per-route
  # CSRF skip (D8): skipping /setup would be a remote passphrase-plant.
  scope "/", GlorboWeb do
    pipe_through :browser

    get "/login", AuthController, :login_form
    post "/login", AuthController, :login_submit
    get "/setup", AuthController, :setup_form
    post "/setup", AuthController, :setup_submit
    post "/logout", AuthController, :logout
  end

  scope "/", GlorboWeb do
    pipe_through [:browser, :dashboard_browser]

    # Plan 04-02 Task 1: dashboard entry + company-scope routes.
    # /health-legacy keeps the Phase 1 health probe available; 04-03
    # mounts HealthLive at /health below.
    get "/", PageController, :redirect_to_companies
    get "/health-legacy", PageController, :health

    # GEP-0053 D1: the LiveView socket bypasses the router pipeline, so the
    # DirectorAuth plug above only gates the dead render. Wrap every
    # dashboard LiveView in a `live_session` whose `on_mount` re-checks the
    # passphrase session on the (connected) socket too — the plug alone is
    # a near-total bypass over the WebSocket.
    live_session :director, on_mount: {GlorboWeb.DirectorAuth, :ensure_director} do
      live "/companies", OverviewLive
      live "/companies/:company", CompanyLive
      live "/companies/:company/kanban", KanbanLive
      live "/companies/:company/projects/:project", ProjectLive
      # Dedicated task-detail page — JIRA-style. Kanban opens the same task
      # as a right-side shelf; clicking "open task page →" navigates here.
      live "/companies/:company/tasks/:task_id", TaskLive
      # GEP-40 chain audit view: task's handoff_chain + reconciled
      # `task.reassign` audit events, for "how did we get here" forensics.
      live "/companies/:company/tasks/:task_id/chain", TaskChainLive
      live "/companies/:company/agents/:agent", AgentLive
      # Unified director inbox — approvals + recent activity + future
      # @mention and assignment feeds. The standalone `/approvals`
      # route was folded in here (backlog #14) — Inbox's Mine tab
      # renders the same awaiting-approval sentinels with approve /
      # deny / archive buttons.
      live "/companies/:company/inbox", InboxLive
      # Plan 04-03 Task 2: content-scope chat view.
      live "/companies/:company/channels/:channel", ChannelLive
      # Plan 04-03 Task 3: audit viewer + system health.
      live "/companies/:company/audit", AuditLive
      # paperclip-ux-gaps §7 — dedicated goals page.
      live "/companies/:company/goals", GoalsLive
      # GEP-28 — agent-created proposals (hire, fire, budget, project,
      # custom). Mirrors the approval queue shape but lives on its own
      # route so the unified inbox isn't the only entry point.
      live "/companies/:company/proposals", ProposalsLive
      # paperclip-ux-gaps §9 — skills marketplace / bundle view.
      # Read-only listing of skills available to this company's agents;
      # "builtin" = ships with Glorbo under priv/templates/skills,
      # "custom" = `<base>/skills/<name>.md` user overrides.
      live "/companies/:company/skills", SkillsLive
      # T1-E brain dump (#230) — daily append-only capture log.
      live "/companies/:company/braindump", BrainDumpLive
      # Localforge bridge #3: unified live activity feed. Subscribes to
      # the global `audit:all` topic; one row per audit append across
      # every company.
      live "/activity", ActivityLive
      live "/health", HealthLive
      # GEP-8 — provider registry dashboard.
      live "/providers", ProvidersLive
      # GEP-26 Phase B — benchmark runs (A/B provider comparison).
      # BenchmarksLive is the index, BenchLive is the per-run blind
      # scoring view. Both read from ~/.glorbo/benchmarks/runs/*.
      live "/benchmarks", BenchmarksLive
      live "/benchmarks/:run_id", BenchLive
      # T2-D (#242) — cross-company monthly cost ledger.
      live "/costs", CostsLive
    end

    # Plain dead-render controller routes — gated by the DirectorAuth plug
    # (they don't run through live_session). Director ↔ agent DM redirect
    # and the audit CSV export.
    get "/companies/:company/dms/:agent", PageController, :redirect_to_dm
    # #259 — CSV export of the current month's audit log.
    get "/companies/:company/audit.csv", AuditExportController, :export
  end

  # T2-B (#232) — Ctrl+K content search. JSON endpoint consumed by the
  # browser palette. GEP-0053: gated by the passphrase session
  # (:dashboard_api), NOT the dashboard_token — otherwise a token-holder
  # without the passphrase could enumerate task titles via
  # `curl /api/search?token=…&co=<slug>&q=<prefix>` even though the
  # dashboard itself is passphrase-gated (codex final review, Medium).
  scope "/api", GlorboWeb do
    pipe_through :dashboard_api

    get "/search", SearchController, :search
  end

  # GEP-29 wave (a) — Model Context Protocol server.
  # Streamable HTTP transport, single endpoint. Wrapped in the
  # `:dashboard` pipeline (threatmodel T11): if `dashboard_token` is
  # configured, MCP clients must pass it via `Authorization: Bearer
  # <token>` or `?token=<token>`. Without a configured token the
  # pipeline is a no-op and loopback binding + host-user trust is the
  # outer boundary. The MCP plug keeps its own Origin check for
  # DNS-rebind protection.
  scope "/" do
    pipe_through :dashboard

    forward "/mcp", GlorboWeb.MCP.Plug
  end
end
