defmodule Mix.Tasks.Glorbo.Docs.FileFormats do
  @moduledoc """
  Generates `docs/file-formats/<kind>.md` — one file per registered
  `Glorbo.FileSpec` module. Content is synthesised from each spec's
  `docs/0` (title + summary + examples), `frontmatter_schema/0`
  (required/optional keys, enums, patterns, caps), and
  `canonical_key_order/0`.

  Part of GEP-25 R26.2b. The matching precommit step runs this task
  with `--check` and fails if the generated tree diverges from the
  committed docs, so a spec edit that changes the public schema
  forces a docs regen in the same commit.

  ## Usage

      mix glorbo.docs.file_formats            # write/overwrite docs
      mix glorbo.docs.file_formats --check    # fail if drift

  Exit code `0` on success (or when `--check` passes clean); `1`
  when `--check` detects drift.
  """
  @shortdoc "Regenerate docs/file-formats/ from FileSpec modules"

  use Mix.Task

  @docs_dir "docs/file-formats"

  @impl Mix.Task
  def run(argv) do
    {opts, _argv, _invalid} =
      OptionParser.parse(argv, strict: [check: :boolean])

    check? = !!opts[:check]

    # Ensure the app is compiled so FileSpec modules are available.
    Mix.Task.run("compile", [])

    rendered = render_all()

    if check? do
      do_check(rendered)
    else
      do_write(rendered)
    end
  end

  # Render one `.md` body per spec. Returns list of
  # `{relative_path, content}` tuples.
  defp render_all do
    Glorbo.FileSpec.specs()
    |> Enum.map(fn mod ->
      docs = mod.docs()
      schema = mod.frontmatter_schema()
      order = mod.canonical_key_order()
      kind = mod.kind()
      filename = kind |> String.replace("/", "_") |> Kernel.<>(".md")
      path = Path.join(@docs_dir, filename)

      {path, render_one(mod, kind, docs, schema, order)}
    end)
    |> then(&[{Path.join(@docs_dir, "README.md"), render_index(&1)} | &1])
  end

  defp render_one(mod, kind, docs, schema, order) do
    """
    # `#{kind}` — #{Map.get(docs, :title, "")}

    <!-- AUTOGENERATED from `#{inspect(mod)}` by
         `mix glorbo.docs.file_formats`. Do not edit by hand;
         regen after changing the spec module. -->

    #{String.trim_trailing(Map.get(docs, :summary, ""))}

    ## Frontmatter schema

    **Required:** #{fmt_key_list(Map.get(schema, :required, []))}

    **Optional:** #{fmt_key_list(Map.get(schema, :optional, []))}

    #{fmt_enums(Map.get(schema, :enums, %{}))}#{fmt_patterns(Map.get(schema, :patterns, %{}))}#{fmt_caps(Map.get(schema, :caps, %{}))}
    ## Canonical key order

    When the formatter rewrites this file, keys appear in this order:

    #{fmt_key_list(order)}

    Unknown keys fall after the known block, sorted alphabetically.

    ## Examples

    #{fmt_examples(Map.get(docs, :examples, []))}
    """
  end

  defp fmt_key_list([]), do: "*(none)*"

  defp fmt_key_list(keys) do
    Enum.map_join(keys, ", ", &"`#{&1}`")
  end

  defp fmt_enums(enums) when map_size(enums) == 0, do: ""

  defp fmt_enums(enums) do
    rows =
      enums
      |> Enum.sort()
      |> Enum.map_join("\n", fn {k, vs} ->
        "| `#{k}` | #{Enum.map_join(vs, ", ", &"`#{&1}`")} |"
      end)

    """
    ### Enums

    | Key | Allowed values |
    |-----|----------------|
    #{rows}

    """
  end

  defp fmt_patterns(patterns) when map_size(patterns) == 0, do: ""

  defp fmt_patterns(patterns) do
    rows =
      patterns
      |> Enum.sort()
      |> Enum.map_join("\n", fn {k, re} -> "| `#{k}` | `#{Regex.source(re)}` |" end)

    """
    ### Patterns

    | Key | Regex |
    |-----|-------|
    #{rows}

    """
  end

  defp fmt_caps(caps) when map_size(caps) == 0, do: ""

  defp fmt_caps(caps) do
    rows =
      caps
      |> Enum.sort()
      |> Enum.map_join("\n", fn {k, n} -> "| `#{k}` | #{n} |" end)

    """
    ### Caps (byte limits)

    | Target | Bytes |
    |--------|-------|
    #{rows}

    """
  end

  defp fmt_examples([]), do: "*(no examples declared)*"

  defp fmt_examples(examples) do
    examples
    |> Enum.map_join("\n\n", fn ex ->
      "```markdown\n#{String.trim_trailing(ex)}\n```"
    end)
  end

  # ------------------------------------------------------------------
  # Index (docs/file-formats/README.md)
  # ------------------------------------------------------------------

  defp render_index(entries) do
    rows =
      entries
      |> Enum.reject(fn {p, _} -> Path.basename(p) == "README.md" end)
      |> Enum.sort_by(fn {p, _} -> Path.basename(p) end)
      |> Enum.map_join("\n", fn {path, _content} ->
        kind =
          path
          |> Path.basename(".md")
          |> String.replace("_", "/")

        rel = Path.basename(path)
        "- [`#{kind}`](./#{rel})"
      end)

    """
    # Glorbo file formats — reference

    <!-- AUTOGENERATED by `mix glorbo.docs.file_formats`. Do not edit
         by hand; regenerate after changing `Glorbo.FileSpec` modules.
         See GEP-25 for the broader spec process. -->

    One entry per `kind:` discriminator shipped under
    `Glorbo.FileSpec`. Each reference page documents the required/
    optional frontmatter keys, enums, patterns, byte caps, canonical
    key order, and at least one worked example.

    ## Kinds

    #{rows}

    ## See also

    - [GEP-25](../geps/0025-file-format-spec-and-tooling.md) —
      file format specs, `kind:` discriminator, `glorbo validate`,
      `glorbo fmt`.
    - `lib/glorbo/file_spec/*.ex` — canonical source for every
      entry in this tree.
    """
  end

  # ------------------------------------------------------------------
  # IO
  # ------------------------------------------------------------------

  defp do_write(rendered) do
    File.mkdir_p!(@docs_dir)

    count =
      Enum.count(rendered, fn {path, content} ->
        existing =
          case File.read(path) do
            {:ok, s} -> s
            _ -> nil
          end

        if existing == content do
          false
        else
          File.write!(path, content)
          true
        end
      end)

    Mix.shell().info(
      "mix glorbo.docs.file_formats — wrote #{count} / #{length(rendered)} file(s)."
    )

    :ok
  end

  defp do_check(rendered) do
    drift =
      Enum.filter(rendered, fn {path, content} ->
        case File.read(path) do
          {:ok, existing} -> existing != content
          _ -> true
        end
      end)

    case drift do
      [] ->
        Mix.shell().info(
          "mix glorbo.docs.file_formats --check — clean " <>
            "(#{length(rendered)} file(s))."
        )

        :ok

      [_ | _] = files ->
        for {path, _} <- files,
            do: Mix.shell().error("drift: #{path}")

        Mix.shell().error(
          "\nRun `mix glorbo.docs.file_formats` to regenerate " <>
            "and commit the result."
        )

        System.at_exit(fn _ -> exit({:shutdown, 1}) end)
        Mix.raise("docs/file-formats drift (#{length(files)} file(s))")
    end
  end
end
