defmodule Mix.Tasks.Glorbo.ReleaseFormula do
  @moduledoc """
  Regenerate the Homebrew formula for the current `mix.exs` version,
  pulling sha256 sums from the already-published GitHub release
  asset manifest.

      mix glorbo.release_formula [--tap-path PATH] [--write]

  By default the task prints the rendered formula to stdout and
  exits 0. Pass `--write` to overwrite `<tap-path>/Formula/glorbo.rb`
  in place.

  `--tap-path` defaults to `../homebrew-tap` (sibling checkout).

  ## Typical flow after a release

      gh release create vX.Y.Z ...          # upload binaries + SHA256SUMS
      mix glorbo.release_formula --write    # regenerate the formula
      (cd ../homebrew-tap && git commit -am "glorbo vX.Y.Z" && git push)

  The task fetches
  `https://github.com/foobarto/glorbo/releases/download/vX.Y.Z/SHA256SUMS`
  over HTTP and parses the two-column `<sha>  <filename>` lines.
  Fails loudly if the release or the expected assets are missing.
  """
  use Mix.Task
  require Logger

  @shortdoc "Regenerate the Homebrew formula for the current mix.exs version"

  @repo "foobarto/glorbo"
  @tap_formula_path "Formula/glorbo.rb"
  @required_assets [
    "glorbo-linux-x86_64",
    "glorbo-linux-aarch64",
    "glorbo-darwin-x86_64",
    "glorbo-darwin-arm64"
  ]

  @impl Mix.Task
  def run(argv) do
    {opts, _argv, _invalid} =
      OptionParser.parse(argv, strict: [tap_path: :string, write: :boolean])

    version = Mix.Project.config()[:version]
    tap_path = Keyword.get(opts, :tap_path, "../homebrew-tap")

    Application.ensure_all_started(:inets)
    Application.ensure_all_started(:ssl)

    shas = fetch_sha256sums(version)
    validate_assets!(shas)

    formula = render_formula(version, shas)

    if opts[:write] do
      target = Path.join(tap_path, @tap_formula_path)
      File.mkdir_p!(Path.dirname(target))
      File.write!(target, formula)
      IO.puts("✓ wrote #{target} (version=#{version})")
    else
      IO.puts(formula)
    end
  end

  # ------------------------------------------------------------------
  # SHA256 fetch
  # ------------------------------------------------------------------

  defp fetch_sha256sums(version) do
    url =
      "https://github.com/#{@repo}/releases/download/v#{version}/SHA256SUMS"

    case :httpc.request(:get, {to_charlist(url), []}, [], body_format: :binary) do
      {:ok, {{_, 200, _}, _headers, body}} ->
        parse_sha256sums(body)

      {:ok, {{_, status, reason}, _, _}} ->
        Mix.raise(
          "SHA256SUMS fetch failed for v#{version}: HTTP #{status} #{reason}\n" <>
            "URL: #{url}\n\n" <>
            "Is the GitHub release published? Was SHA256SUMS uploaded?"
        )

      {:error, reason} ->
        Mix.raise("SHA256SUMS fetch failed: #{inspect(reason)}")
    end
  end

  defp parse_sha256sums(body) when is_binary(body) do
    body
    |> String.split("\n", trim: true)
    |> Enum.reduce(%{}, fn line, acc ->
      case String.split(line, ~r/\s+/, parts: 2) do
        [sha, filename] -> Map.put(acc, String.trim(filename), String.trim(sha))
        _ -> acc
      end
    end)
  end

  defp validate_assets!(shas) do
    for asset <- @required_assets do
      unless Map.has_key?(shas, asset) do
        Mix.raise(
          "SHA256SUMS missing required asset `#{asset}` — did the release " <>
            "ship both x86_64 and aarch64 Burrito binaries?"
        )
      end
    end

    :ok
  end

  # ------------------------------------------------------------------
  # Formula rendering
  # ------------------------------------------------------------------

  defp render_formula(version, shas) do
    linux_x86 = Map.fetch!(shas, "glorbo-linux-x86_64")
    linux_arm = Map.fetch!(shas, "glorbo-linux-aarch64")
    macos_x86 = Map.fetch!(shas, "glorbo-darwin-x86_64")
    macos_arm = Map.fetch!(shas, "glorbo-darwin-arm64")

    version_regex = String.replace(version, ".", "\\\\.")

    """
    # typed: false
    # frozen_string_literal: true

    # Homebrew formula for Glorbo — filesystem-first agent orchestration.
    #
    # Pre-1.0. Linux: full kernel-sandboxed agent runtime via bwrap
    # (GEP-5). macOS: degraded mode — agents run unsandboxed because
    # bwrap has no macOS equivalent yet. See caveats.
    #
    # AUTO-GENERATED by `mix glorbo.release_formula` — do not edit
    # by hand. Regenerate after each release:
    #
    #   gh release create vX.Y.Z ...
    #   mix glorbo.release_formula --write
    class Glorbo < Formula
      desc "Filesystem-first agent orchestration (Elixir/OTP + Phoenix LiveView)"
      homepage "https://github.com/foobarto/glorbo"
      version "#{version}"
      license "Apache-2.0"

      on_linux do
        # bwrap is the kernel-enforced sandbox around every agent
        # subprocess (GEP-5 D4). Linux-only: macOS has no equivalent
        # yet, so the formula omits the dependency there.
        depends_on "bubblewrap"

        on_intel do
          url "https://github.com/foobarto/glorbo/releases/download/v#{version}/glorbo-linux-x86_64"
          sha256 "#{linux_x86}"
        end

        on_arm do
          url "https://github.com/foobarto/glorbo/releases/download/v#{version}/glorbo-linux-aarch64"
          sha256 "#{linux_arm}"
        end
      end

      on_macos do
        on_intel do
          url "https://github.com/foobarto/glorbo/releases/download/v#{version}/glorbo-darwin-x86_64"
          sha256 "#{macos_x86}"
        end

        on_arm do
          url "https://github.com/foobarto/glorbo/releases/download/v#{version}/glorbo-darwin-arm64"
          sha256 "#{macos_arm}"
        end
      end

      def install
        # Burrito ships a single self-contained binary. Pick the right
        # downloaded file by OS + CPU and rename to `glorbo`.
        binary =
          if OS.mac?
            Hardware::CPU.intel? ? "glorbo-darwin-x86_64" : "glorbo-darwin-arm64"
          else
            Hardware::CPU.intel? ? "glorbo-linux-x86_64" : "glorbo-linux-aarch64"
          end

        bin.install binary => "glorbo"
        chmod 0755, bin/"glorbo"
      end

      def caveats
        <<~EOS
          Glorbo is pre-1.0. APIs, CLI flags, on-disk layout, and the
          SQLite schema may change between minor versions.

          First-run setup:
            glorbo doctor          # verify host prerequisites
            glorbo init            # scaffold ~/.glorbo/ with an acme example
            glorbo up              # start the dashboard on :4000

          Platform notes:

            Linux  — agents run in a bwrap-sandboxed subprocess (GEP-5).
                     `brew install bubblewrap` is declared as a dep.

            macOS  — experimental. Agents run UNSANDBOXED because bwrap
                     has no macOS equivalent yet. `glorbo doctor` flags
                     this with a warning; a single audit row lands at
                     first dispatch (`agent.sandbox_unavailable`).
                     FSEvents covers the filesystem-watcher side.

          Docs: \#{homepage}
        EOS
      end

      test do
        # Doctor in JSON mode returns the version + check list.
        output = shell_output("\#{bin}/glorbo doctor --json")
        assert_match(/"version":\\s*"#{version_regex}"/, output)
        assert_match(/"checks":/, output)
      end
    end
    """
  end
end
