defmodule Glorbo.FileSpec.ConfigMd do
  @moduledoc """
  Spec for `~/.glorbo/config.md` — the workspace-level config file
  generated by `Glorbo.Filesystem.Hierarchy.materialise!/1` on first
  boot. Carries boot secrets (Phoenix secret_key_base, optional
  dashboard token, Erlang cookie) plus bind host/port.
  """
  @behaviour Glorbo.FileSpec

  @path_regex ~r{(^|/)config\.md\z}

  @impl true
  def kind, do: "config/v1"

  @impl true
  def path_match?(path) when is_binary(path) do
    # Match only when at the workspace root (not inside a company dir).
    Regex.match?(@path_regex, path) and
      not String.contains?(path, "/companies/")
  end

  @impl true
  def frontmatter_schema do
    %{
      required: [:kind, :secret_key_base, :erl_cookie, :host, :port],
      optional: [:dashboard_token, :created_at],
      enums: %{},
      patterns: %{},
      caps: %{}
    }
  end

  @impl true
  def canonical_key_order do
    [
      :kind,
      :secret_key_base,
      :dashboard_token,
      :erl_cookie,
      :host,
      :port,
      :created_at
    ]
  end

  @impl true
  def docs do
    %{
      title: "config.md — workspace configuration",
      summary: """
      Workspace-level config generated on first boot. Holds secrets
      (secret_key_base, erl_cookie) and network bind (host, port).
      Edit `host: "0.0.0.0"` to accept LAN connections; set
      `dashboard_token:` to gate the dashboard with `?token=<...>`.
      Keep this file readable only by the director.
      """,
      examples: [
        """
        ---
        kind: config/v1
        secret_key_base: <base64 64 bytes>
        dashboard_token: null
        erl_cookie: <24 bytes>
        host: "127.0.0.1"
        port: 4000
        ---

        # Glorbo configuration

        Edit as needed on first run.
        """
      ]
    }
  end
end
